### Get all customers from DB
GET http://localhost:3000/customers

### Get customer By ID
GET http://localhost:3000/customers/688cefd7e176c9be90f79a94

### Get customer By username
GET http://localhost:3000/customers/diego0812

### Creating a customer
POST http://localhost:3000/customers HTTP/1.1
Content-Type: application/json

{
    "firstName": "Diego2",
    "lastName": "Rodriguez",
    "email": "diegorodriguez@gmail.com",
    "password": "diego2",
    "username": "diego0812"
}

### Updating a user by ID
PUT http://localhost:3000/customers/688cf39c411d81560d15fe33 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Diego",
    "lastName": "Rodriguez",
    "email": "diegorodriguez@gmail.com",
    "password": "diego",
    "username": "new_username"
}

### Deleting users
DELETE http://localhost:3000/customers/689514a87790f25d0b46fbdb

# ======================================================
#                     ORDERS SECTION
# ======================================================

### Creating a new order
POST http://localhost:3000/orders HTTP/1.1
Content-Type: application/json

{
    "customerId": "688cefd7e176c9be90f79a94",
    "productIds": ["6897fc99c2739fafbe27ec76"]
}

### Deleting orders
DELETE http://localhost:3000/orders/{orderId}

### Getting order by customer
GET http://localhost:3000/orders/customer/688cefd7e176c9be90f79a94

### Updating an order
PUT http://localhost:3000/orders/6898004cee02105fe0c0bca0 HTTP/1.1
Content-Type: application/json

{
    "customerId": "688cefd7e176c9be90f79a94",
    "productIds": ["6897fc99c2739fafbe27ec76", "689801e2c2739fafbe27ec7a"]
}